apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  annotations:
    backstage.io/editable-fields: |
      deployment.yaml:
        - spec.replicas
        - spec.template.spec.containers[].image
      services.yaml:
        - spec.ports[].port
        - spec.ports[].targetPort
  name: user-service
  description: A microservice responsible for managing user data.
  tags:
    - microservice
    - user-management
spec:
  type: service
  lifecycle: production
  owner: team-alpha
  system: user-management-system
